config/routes.rb
Rails.application.routes.draw do
  resources :subcategories
  resources :vendors
 get 'ajax_calls/check_email_taken'
 get 'ajax_calls/find_sub_categories'
  get 'dashboard/home'

  get 'dashboard/categories'

  get 'dashboard/products'

  get 'dashboard/users'

  get 'dashboard/reviews'

  get 'dashboard/orders'

  devise_for :users
  get 'home/index'
  get 'home/about'
  get 'home/contact'

  resources :orders
  resources :addresses
  resources :reviews
  resources :cart_line_items
  resources :products
  resources :wishlists
  resources :categories

  root 'home#index'

end

app/models/address.rb
class Address < ActiveRecord::Base
	belongs_to :order
	validates_presence_of :user_id, :street, :pin, :city, :landmark
	validates_numericality_of :user_id, :pin
	validates :pin, length: { maximum: 6 }
end

app/models/bank_customer.rb
class BankCustomer < ActiveRecord::Base
	validates_presence_of :name, :acc_no, :balance
	validates_numericality_of :balance,greater_than_or_equal_to:0
	validates_uniqueness_of :name, :acc_no

def transaction(amount,code)
	if code ==0
		if self.balance < amount
			puts "Insufficent funds"
		else
			self.balance  = self.balance - amount
			self.update_attributes(balance: self.balance)
		end
	else
		self.balance += amount
		self.update_attributes(balance: self.balance)
	end
end
end

app/models/cart_line_item.rb
class CartLineItem < ActiveRecord::Base
	belongs_to :user
	belongs_to :product

	validates_presence_of :user_id, :product_id, :quantity
	validates_numericality_of :user_id, :product_id
	validates_numericality_of :quantity, within: 1..10

	def save_or_update
		line_item = CartLineItem.find_by(user_id: self.user_id, product_id: self.product_id)
		if line_item.nil?
			self.save
		else
			line_item.update_attributes(quantity: line_item.quantity + self.quantity)
		end
	end
end

app/models/category.rb
class Category < ActiveRecord::Base
has_many :products
validates_presence_of :name
validates_uniqueness_of :name
has_many :subcategories
end

app/models/install.rb
class Install < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/order.rb
class Order < ActiveRecord::Base
belongs_to :user
has_many :order_line_items

validates_presence_of :user_id, :order_number, :order_date

after_create :copy_cart_line_items_to_order_line_items
after_create :empty_cart_line_items
after_create :calculate_total
	def copy_cart_line_items_to_order_line_items
	user = self.user
	user.cart_line_items.each do |line_item|
		order_line_item = OrderLineItem.new
		order_line_item.product_id = line_item.product_id
		order_line_item.quantity = line_item.quantity
		order_line_item.price = line_item.product.price
		order_line_item.total = line_item.quantity * line_item.product.price
		order_line_item.order_id = self.id
		order_line_item.save
	end
	end
	def empty_cart_line_items
		user = self.user
		CartLineItem.delete(user.cart_line_items)
	end

	def calculate_total
			self.update_attributes(total: self.order_line_items.sum(:total))
	end

end
 

app/models/order_line_item.rb
class OrderLineItem < ActiveRecord::Base
belongs_to :order
belongs_to :product
end

app/models/product.rb
class Product < ActiveRecord::Base
	belongs_to :category
	belongs_to :subcategory
	validates_presence_of :name, :price, :category_id, :description
	validates_numericality_of :price, :category_id, greater_than_or_equal_to: 1
	has_many :cart_line_items
	has_many :order_line_items
	has_many :reviews
	has_many :wishlists
end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :product
	validates_presence_of :product_id, :user_id, :body, :rating
	validates_numericality_of :product_id, :user_id

end

app/models/subcategory.rb
class Subcategory < ActiveRecord::Base
	belongs_to :category
	has_many :products
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :cart_line_items
	has_many :orders
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/vendor.rb
class Vendor < ActiveRecord::Base
	validates :name, :mobile, :email, presence:true
	validates  :mobile, :email, uniqueness:true
end

app/models/wishlist.rb
class Wishlist < ActiveRecord::Base
belongs_to :product
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def home
  end

  def categories
    @categories = Category.all
  end

  def products
  @products = Product.all
  end

  def users
    @users = User.all
  end

  def reviews
  end

  def orders
    @orders = Order.all
   @users = User.all
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/vendors_helper.rb
module VendorsHelper
end

app/helpers/wishlists_helper.rb
module WishlistsHelper
end

app/views/dashboard/_nav.html.erb
<%= link_to "products",  dashboard_products_path %>

<%= link_to "categories",  dashboard_categories_path %>

<%= link_to "users",  dashboard_users_path %>

<%= link_to "orders",  dashboard_orders_path %>

app/views/dashboard/categories.html.erb
<h2>Dashboard Categories </h2>
<%= render 'nav' %>

<% data= {} %>

<h3>distribution of products across categories</h3>
<% @categories.each do |category|%>
	<% data[category.name] = category.products.length %>
	<% end %>

	<%= pie_chart(data) %>
	<%= column_chart(data) %>
	<%= bar_chart(data) %>
	<%= line_chart(data) %>

<% sales_data = {} %>


<h3> sale of products by categories </h3>
<% @categories.each do |category| %>
	<% sales_data[category.name]= OrderLineItem.joins(:product).where('products.category_id = ?', category.id).length %>
	<% end %>
	<%= column_chart(sales_data) %>
	<%= pie_chart(sales_data) %>

<h3> Total sales Amount across categories </h3>
<% data_amount = {} %>
<% @categories.each do |category| %>
<% data_amount[category.name]= OrderLineItem.joins(:product).where('products.category_id=?',category.id).sum(:total) %>
<% end %>
<%= column_chart(sales_data) %>
<%= pie_chart(sales_data) %>

app/views/dashboard/home.html.erb
<h1>Dashboard#home</h1>
<p>Find me in app/views/dashboard/home.html.erb</p>

app/views/dashboard/orders.html.erb
<h1>Dashboard#orders</h1>
<%= render 'nav' %>
<% user_data = {}  %>


<% @users.each do |user| %>

<% if user.is_admin? %>
<h2> admin </h2>
<% else %>
<% user_data[user.username] = user.orders.length%>
<% end %>
<% end %>
<%= column_chart(user_data)%>

<h2> renevue data </h2>

<% u_data = {} %>
<% @users.each do |user| %>

<% if user.is_admin? %>
<h2> admin </h2>
<% else %>
<% u_data[user.username] = user.orders.pluck(:total).sum(:total) %>
<% end %>
<% end %>
<%= column_chart(u_data)%>

app/views/dashboard/products.html.erb
<h2> dashboard products </h2>
<%= render 'nav' %>

<% data_product = {} %>
<% @products.each do |product| %>
<% data_product[product.name] = product.reviews.length %>
<% end %>

<%=pie_chart(data_product) %>

app/views/dashboard/reviews.html.erb
<h1>Dashboard#reviews</h1>
<p>Find me in app/views/dashboard/reviews.html.erb</p>

app/views/dashboard/users.html.erb
<h1>Dashboard#users</h1>
<p>Find me in app/views/dashboard/users.html.erb</p>