config/routes.rb
Rails.application.routes.draw do
  resources :subcategories
  resources :vendors
 get 'ajax_calls/check_email_taken'
 get 'ajax_calls/find_sub_categories'
  get 'dashboard/home'

  get 'dashboard/categories'

  get 'dashboard/products'

  get 'dashboard/users'

  get 'dashboard/reviews'

  get 'dashboard/orders'

  devise_for :users
  get 'home/index'
  get 'home/about'
  get 'home/contact'

  resources :orders
  resources :addresses
  resources :reviews
  resources :cart_line_items
  resources :products
  resources :wishlists
  resources :categories

  root 'home#index'

end

app/models/address.rb
class Address < ActiveRecord::Base
	belongs_to :order
	validates_presence_of :user_id, :street, :pin, :city, :landmark
	validates_numericality_of :user_id, :pin
	validates :pin, length: { maximum: 6 }
end

app/models/bank_customer.rb
class BankCustomer < ActiveRecord::Base
	validates_presence_of :name, :acc_no, :balance
	validates_numericality_of :balance,greater_than_or_equal_to:0
	validates_uniqueness_of :name, :acc_no

def transaction(amount,code)
	if code ==0
		if self.balance < amount
			puts "Insufficent funds"
		else
			self.balance  = self.balance - amount
			self.update_attributes(balance: self.balance)
		end
	else
		self.balance += amount
		self.update_attributes(balance: self.balance)
	end
end
end

app/models/cart_line_item.rb
class CartLineItem < ActiveRecord::Base
	belongs_to :user
	belongs_to :product

	validates_presence_of :user_id, :product_id, :quantity
	validates_numericality_of :user_id, :product_id
	validates_numericality_of :quantity, within: 1..10

	def save_or_update
		line_item = CartLineItem.find_by(user_id: self.user_id, product_id: self.product_id)
		if line_item.nil?
			self.save
		else
			line_item.update_attributes(quantity: line_item.quantity + self.quantity)
		end
	end
end

app/models/category.rb
class Category < ActiveRecord::Base
has_many :products
validates_presence_of :name
validates_uniqueness_of :name
has_many :subcategories
end

app/models/install.rb
class Install < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/order.rb
class Order < ActiveRecord::Base
belongs_to :user
has_many :order_line_items

validates_presence_of :user_id, :order_number, :order_date

after_create :copy_cart_line_items_to_order_line_items
after_create :empty_cart_line_items
after_create :calculate_total
	def copy_cart_line_items_to_order_line_items
	user = self.user
	user.cart_line_items.each do |line_item|
		order_line_item = OrderLineItem.new
		order_line_item.product_id = line_item.product_id
		order_line_item.quantity = line_item.quantity
		order_line_item.price = line_item.product.price
		order_line_item.total = line_item.quantity * line_item.product.price
		order_line_item.order_id = self.id
		order_line_item.save
	end
	end
	def empty_cart_line_items
		user = self.user
		CartLineItem.delete(user.cart_line_items)
	end

	def calculate_total
			self.update_attributes(total: self.order_line_items.sum(:total))
	end

end
 

app/models/order_line_item.rb
class OrderLineItem < ActiveRecord::Base
belongs_to :order
belongs_to :product
end

app/models/product.rb
class Product < ActiveRecord::Base
	belongs_to :category
	belongs_to :subcategory
	validates_presence_of :name, :price, :category_id, :description
	validates_numericality_of :price, :category_id, greater_than_or_equal_to: 1
	has_many :cart_line_items
	has_many :order_line_items
	has_many :reviews
	has_many :wishlists
end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :product
	validates_presence_of :product_id, :user_id, :body, :rating
	validates_numericality_of :product_id, :user_id

end

app/models/subcategory.rb
class Subcategory < ActiveRecord::Base
	belongs_to :category
	has_many :products
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :cart_line_items
	has_many :orders
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/vendor.rb
class Vendor < ActiveRecord::Base
	validates :name, :mobile, :email, presence:true
	validates  :mobile, :email, uniqueness:true
end

app/models/wishlist.rb
class Wishlist < ActiveRecord::Base
belongs_to :product
end

app/controllers/subcategories_controller.rb
class SubcategoriesController < ApplicationController
  before_action :set_subcategory, only: [:show, :edit, :update, :destroy]

  # GET /subcategories
  # GET /subcategories.json
  def index
    @subcategories = Subcategory.all
   
  end

  # GET /subcategories/1
  # GET /subcategories/1.json
  def show
  end

  # GET /subcategories/new
  def new
    @subcategory = Subcategory.new
  end

  # GET /subcategories/1/edit
  def edit
  end

  # POST /subcategories
  # POST /subcategories.json
  def create
    @subcategory = Subcategory.new(subcategory_params)

    respond_to do |format|
      if @subcategory.save
        format.html { redirect_to @subcategory, notice: 'Subcategory was successfully created.' }
        format.json { render :show, status: :created, location: @subcategory }
      else
        format.html { render :new }
        format.json { render json: @subcategory.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subcategories/1
  # PATCH/PUT /subcategories/1.json
  def update
    respond_to do |format|
      if @subcategory.update(subcategory_params)
        format.html { redirect_to @subcategory, notice: 'Subcategory was successfully updated.' }
        format.json { render :show, status: :ok, location: @subcategory }
      else
        format.html { render :edit }
        format.json { render json: @subcategory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subcategories/1
  # DELETE /subcategories/1.json
  def destroy
    @subcategory.destroy
    respond_to do |format|
      format.html { redirect_to subcategories_url, notice: 'Subcategory was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subcategory
      @subcategory = Subcategory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subcategory_params
      params.require(:subcategory).permit(:name, :category_id)
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/subcategories_helper.rb
module SubcategoriesHelper
end

app/helpers/vendors_helper.rb
module VendorsHelper
end

app/helpers/wishlists_helper.rb
module WishlistsHelper
end

app/views/subcategories/_form.html.erb
<%= form_for(@subcategory) do |f| %>
  <% if @subcategory.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subcategory.errors.count, "error") %> prohibited this subcategory from being saved:</h2>

      <ul>
      <% @subcategory.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :category_name %><br>
<%= f.collection_select :category_id, Category.all, :id, :name, prompt: "Select Category" %><br /><br />   
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/subcategories/edit.html.erb
<h1>Editing Subcategory</h1>

<%= render 'form' %>

<%= link_to 'Show', @subcategory %> |
<%= link_to 'Back', subcategories_path %>

app/views/subcategories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Subcategories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subcategories.each do |subcategory| %>
      <tr>
        <td><%= subcategory.name %></td>
        <td><%= subcategory.category_id %></td>
        <td><%= link_to 'Show', subcategory %></td>
        <td><%= link_to 'Edit', edit_subcategory_path(subcategory) %></td>
        <td><%= link_to 'Destroy', subcategory, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Subcategory', new_subcategory_path %>

app/views/subcategories/new.html.erb
<h1>New Subcategory</h1>

<%= render 'form' %>


<%= link_to 'Back', subcategories_path %>

app/views/subcategories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @subcategory.name %>
</p>

<p>
  <strong>Listing products</strong>
  <ol>
  <% @subcategory.products.each do |product| %>
 <li><%= link_to product.name, product_path(product.id) %></li>
 <ul>
 <%# @subcategory.products.each do |product| %>
 <% product.reviews.each do |review| %>
 <li><%= review.body %></li>
 <% end %>
 <%# end %>
 </ul>
 <% end %>

 </ol>
 <strong> 


</p>

<%= link_to 'Edit', edit_subcategory_path(@subcategory) %> |
<%= link_to 'Back', subcategories_path %>